/* DATATYPE */
say "Look for DATATYPE OK"
/* These from the Rexx book. */
if datatype(' 12 ') \== 'NUM' then say 'failed in test 1 '
if datatype('') \== 'CHAR' then say 'failed in test 2 '
if datatype('123*') \== 'CHAR' then say 'failed in test 3 '
if datatype('12.3','N') \= 1 then say 'failed in test 4 '
if datatype('12.3','W') \= 0 then say 'failed in test 5 '
if datatype('Fred','M') \= 1 then say 'failed in test 6 '
if datatype('','M') \= 0 then say 'failed in test 7 '
if datatype('Minx','L') \= 0 then say 'failed in test 8 '
/* This one depends on which characters are "extra letters" */
if datatype('3d?','s') \= 1 then say 'failed in test 9 '
if datatype('BCd3','X') \= 1 then say 'failed in test 10 '
if datatype('BC d3','X') \= 1 then say 'failed in test 11 '
/* These from Mark Hessling. */
if datatype("foobar") \== "CHAR" then say 'failed in test 12 '
if datatype("foo bar") \== "CHAR" then say 'failed in test 13 '
if datatype("123.456.789") \== "CHAR" then say 'failed in test 14 '
if datatype("123.456") \== "NUM" then say 'failed in test 15 '
if datatype("") \== "CHAR" then say 'failed in test 16 '
if datatype("DeadBeef" , 'A') \== "1" then say 'failed in test 17 '
if datatype("Dead Beef",'A') \== "0" then say 'failed in test 18 '
if datatype("1234ABCD",'A') \== '1' then say 'failed in test 19 '
if datatype("",'A') \== "0" then say 'failed in test 20 '
if datatype("foobar",'B') \== "0" then say 'failed in test 21 '
if datatype("01001101",'B') \== "1" then say 'failed in test 22 '
/*if datatype("0110 1101",'B') \== "1" then say 'failed in test 23 '
if datatype("",'B') \== "1" then say 'failed in test 24 ' these fail on z/VM */
if datatype("foobar",'L') \== "1" then say 'failed in test 25 '
if datatype("FooBar",'L') \== "0" then say 'failed in test 26 '
if datatype("foo bar",'L') \== "0" then say 'failed in test 27 '
if datatype("",'L') \== "0" then say 'failed in test 28 '
if datatype("foobar",'M') \== "1" then say 'failed in test 29 '
if datatype("FooBar",'M') \== "1" then say 'failed in test 30 '
if datatype("foo bar",'M') \== "0" then say 'failed in test 31 '
if datatype("FOOBAR",'M') \== "1" then say 'failed in test 32 '
if datatype("",'M') \== "0" then say 'failed in test 33 '
if datatype("foo bar",'N') \== "0" then say 'failed in test 34 '
if datatype("1324.1234",'N') \== "1" then say 'failed in test 35 '
if datatype("123.456.789",'N') \== "0" then say 'failed in test 36 '
if datatype("",'N') \== "0" then say 'failed in test 37 '
if datatype("foo bar",'S') \== "0" then say 'failed in test 38 '
if datatype("??@##_Foo$Bar!!!",'S') \== "1" then say 'failed in test 39'
if datatype("",'S') \== "0" then say 'failed in test 40 '
if datatype("foo bar",'U') \== "0" then say 'failed in test 41 '
if datatype("Foo Bar",'U') \== "0" then say 'failed in test 42 '
if datatype("FOOBAR",'U') \== "1" then say 'failed in test 43 '
if datatype("",'U') \== "0" then say 'failed in test 44 '
if datatype("Foobar",'W') \== "0" then say 'failed in test 45 '
if datatype("123",'W') \== "1" then say 'failed in test 46 '
if datatype("12.3",'W') \== "0" then say 'failed in test 47 '
if datatype("",'W') \== "0" then say 'failed in test 48 '
if datatype('123.123','W') \== '0' then say 'failed in test 49 '
if datatype('123.123E3','W') \== '1' then say 'failed in test 50 '
if datatype('123.0000003','W') \== '1' then say 'failed in test 51 '
if datatype('123.0000004','W') \== '1' then say 'failed in test 52 '
if datatype('123.0000005','W') \== '0' then say 'failed in test 53 '
if datatype('123.0000006','W') \== '0' then say 'failed in test 54 '
if datatype(' 23','W') \== '1' then say 'failed in test 55 '
if datatype(' 23 ','W') \== '1' then say 'failed in test 56 '
if datatype('23 ','W') \== '1' then say 'failed in test 57 '
if datatype('123.00','W') \== '1' then say 'failed in test 58 '
if datatype('123000E-2','W') \== '1' then say 'failed in test 59 '
if datatype('123000E+2','W') \== '1' then say 'failed in test 60 '
if datatype("Foobar",'X') \== "0" then say 'failed in test 61 '
if datatype("DeadBeef",'X') \== "1" then say 'failed in test 62 '
if datatype("A B C",'X') \== "0" then say 'failed in test 63 '
if datatype("A BC DF",'X') \== "1" then say 'failed in test 64 '
if datatype("123ABC",'X') \== "1" then say 'failed in test 65 '
if datatype("123AHC",'X') \== "0" then say 'failed in test 66 '
if datatype("",'X') \== "1" then say 'failed in test 67 '
if datatype('0.000E-2','w') \== '1' then say 'failed in test 68 '
if datatype('0.000E-1','w') \== '1' then say 'failed in test 69 '
if datatype('0.000E0','w') \== '1' then say 'failed in test 70 '
if datatype('0.000E1','w') \== '1' then say 'failed in test 71 '
if datatype('0.000E2','w') \== '1' then say 'failed in test 72 '
if datatype('0.000E3','w') \== '1' then say 'failed in test 73 '
if datatype('0.000E4','w') \== '1' then say 'failed in test 74 '
if datatype('0.000E5','w') \== '1' then say 'failed in test 75 '
if datatype('0.000E6','w') \== '1' then say 'failed in test 76 '
if datatype('0E-1','w') \== '1' then say 'failed in test 77 '
if datatype('0E0','w') \== '1' then say 'failed in test 78 '
if datatype('0E1','w') \== '1' then say 'failed in test 79 '
if datatype('0E2','w') \== '1' then say 'failed in test 80 '
say "DATATYPE OK"
